# Generated by Django 2.1.7 on 2019-02-28 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterField(
            model_name='category',
            name='photo',
            field=models.ImageField(default='static/default-img.png', upload_to='categories_photos'),
        ),
        migrations.AlterField(
            model_name='collection',
            name='photo',
            field=models.ImageField(default='static/default-img.png', upload_to='collections_photos'),
        ),
        migrations.AlterField(
            model_name='item',
            name='photo',
            field=models.ImageField(default='static/default-img.png', upload_to='items_photos'),
        ),
    ]
