# Generated by Django 2.1.7 on 2019-03-02 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0002_auto_20190227_2130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collection',
            name='photo',
            field=models.ImageField(default='default-img.png', upload_to='collections_photos'),
        ),
    ]
