# Generated by Django 2.1.7 on 2019-03-02 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0004_auto_20190301_2210'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='photo',
            field=models.ImageField(default='default-img.png', upload_to='items_photos'),
        ),
    ]
