# Generated by Django 2.1.7 on 2019-03-03 01:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0006_auto_20190302_2051'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='photo',
        ),
    ]
