# Generated by Django 2.1.7 on 2019-03-03 02:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0007_remove_category_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collection',
            name='description',
        ),
    ]
