# Generated by Django 2.1.7 on 2019-03-04 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0008_remove_collection_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='photo',
            field=models.ImageField(default='default-image.png', upload_to='items_photos'),
        ),
    ]
